### ISSUE TITLE
Ошибка компиляции

### ISSUE THREAD

**Issue by Metr-FM** [AlexIII/gsmGuard#1]
Arduino: 1.8.19 (Windows 7), Плата:"Arduino Nano, ATmega168"
При комплекции скетча выдает ошибку.

gsmGuard-firmware:39:4: error: #error "F_CPU is not 8 MHz! Select board with 8MHz clock even if you actually use 16MHz. (in which case also #define F_CPU_16MHZ at the beginning of *.ino file)"

   #error "F_CPU is not 8 MHz! Select board with 8MHz clock even if you actually use 16MHz. (in which case also #define F_CPU_16MHZ at the beginning of *.ino file)"

    ^~~~~

exit status 1

#error "F_CPU is not 8 MHz! Select board with 8MHz clock even if you actually use 16MHz. (in which case also #define F_CPU_16MHZ at the beginning of *.ino file)"

**Comment by AlexIII** [comment]
Следуйте инструкциям, которые даны в тексте ошибки: раскомментируйте `#define F_CPU_16MHZ`  и выберете плату 8MHz в настройках проекта.

**Comment by Metr-FM** [comment]
раскомментируйте #define F_CPU_16MHZ
и выбрал в настройках программы (через Инструменты) Arduino Nano, ATmega168.
Результат такой же. Что делаю не так?

Arduino: 1.8.19 (Windows 7), Плата:"Arduino Nano, ATmega168"

gsmGuard-firmware:39:4: error: #error "F_CPU is not 8 MHz! Select board with 8MHz clock even if you actually use 16MHz. (in which case also #define F_CPU_16MHZ at the beginning of *.ino file)"

   #error "F_CPU is not 8 MHz! Select board with 8MHz clock even if you actually use 16MHz. (in which case also #define F_CPU_16MHZ at the beginning of *.ino file)"

    ^~~~~

exit status 1

#error "F_CPU is not 8 MHz! Select board with 8MHz clock even if you actually use 16MHz. (in which case also #define F_CPU_16MHZ at the beginning of *.ino file)"

**Comment by AlexIII** [comment]
![image](https://user-images.githubusercontent.com/10047074/210789833-77f2f544-0c77-463e-9283-2d202d309d40.png)

**Comment by Metr-FM** [comment]
Исправил. вышла новая ошибка.

Arduino: 1.8.19 (Windows 7), Плата:"Arduino Pro or Pro Mini, ATmega328P (3.3V, 8 MHz)"

In file included from D:\Arduino Projects\gsmGuard-firmware\Hardware.h:13:0,

                 from D:\Arduino Projects\gsmGuard-firmware\Status.h:10,

                 from D:\Arduino Projects\gsmGuard-firmware\gsmGuard-firmware.ino:34:

D:\Arduino Projects\gsmGuard-firmware\TempHistory.h: In member function 'void TempHistory::dumpCSV(Stream&, char) const':

D:\Arduino Projects\gsmGuard-firmware\TempHistory.h:48:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

     for(int i = 0; i < samples.size(); ++i) {

                    ~~^~~~~~~~~~~~~~~~

In file included from D:\Arduino Projects\gsmGuard-firmware\Status.h:10:0,

                 from D:\Arduino Projects\gsmGuard-firmware\gsmGuard-firmware.ino:34:

D:\Arduino Projects\gsmGuard-firmware\Hardware.h: In static member function 'static Hardware::Sensors Hardware::sensors()':

D:\Arduino Projects\gsmGuard-firmware\Hardware.h:88:59: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

     if((cur - tempHistory.lastEntryTime()).totalseconds() > 2UL*3600UL) //2 hr.

        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~

In file included from D:\Arduino Projects\gsmGuard-firmware\Events.h:8:0,

                 from D:\Arduino Projects\gsmGuard-firmware\Status.h:11,

                 from D:\Arduino Projects\gsmGuard-firmware\gsmGuard-firmware.ino:34:

D:\Arduino Projects\gsmGuard-firmware\Event.h: In member function 'const __FlashStringHelper* Event::name() const':

D:\Arduino Projects\gsmGuard-firmware\Event.h:68:11: warning: enumeration value 'NO_EVENT' not handled in switch [-Wswitch]

     switch(n) {

           ^

In file included from D:\Arduino Projects\gsmGuard-firmware\Status.h:12:0,

                 from D:\Arduino Projects\gsmGuard-firmware\gsmGuard-firmware.ino:34:

D:\Arduino Projects\gsmGuard-firmware\Config.h: In member function 'bool Config::SchEntry::isActive() const':

Config.h:56:31: error: 'const class DateTime' has no member named 'dayOfTheWeek'; did you mean 'dayOfWeek'?

       const uint8_t dw = (now.dayOfTheWeek()+6)%7;

                               ^~~~~~~~~~~~

                               dayOfWeek

In file included from D:\Arduino Projects\gsmGuard-firmware\gsmGuard-firmware.ino:34:0:

D:\Arduino Projects\gsmGuard-firmware\Status.h: In member function 'void Status::upd()':

D:\Arduino Projects\gsmGuard-firmware\Status.h:84:58: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

         if((Hardware::now() - prv.time()).totalseconds() > timeout)

            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~

D:\Arduino Projects\gsmGuard-firmware\gsmGuard-firmware.ino: In function 'ConfigAction getConfigStr(Stream&, char*, size_t, bool)':

D:\Arduino Projects\gsmGuard-firmware\gsmGuard-firmware.ino:73:10: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

     if(r >= confBuffSz-1) {

        ~~^~~~~~~~~~~~~~~

exit status 1

'const class DateTime' has no member named 'dayOfTheWeek'; did you mean 'dayOfWeek'?

**Comment by AlexIII** [comment]
Скорее всего не та библиотека RTC или другая версия. Нужна именно та, которая указана.

**Comment by Metr-FM** [comment]
Обновил все библиотеки как в описании по версии, компиляция прошла успешно, спасибо Александр!

Начал разбираться по схемотехнике и назначению пинов из скетча.
Верно ли определил что за  что отвечает? и за что отвечают другие пины, где я не прописал их назначение

#define LIGHT_PIN A0        //датчик освещенности
#define TEMP_PIN 9          //датчик температуры 1-wire  ?
#define BAT_PIN A1          //контроль Uакб
#define DOOR_PIN 7          //герконовый датчик на дверь
#define PIR_PIN 6           //датчик движения
#define EXT1_PIN 10
#define EXT2_PIN 11
#define BUZZER_PIN 8        //звуковая сирена
#define POWER_PIN 13        //
#define USB_POWER_DETECT 12 // датчик подключени USB

По схемотехнике вопросы не совсем понятно за что отвечают каскады. подскажите пожалуйста:
1) R3, R4, R5
2) чем управляет мосфет транзистор Q1?
3) разъемы J2 и J3 это для доработки самим или как.
4) для чего нужны ext1, ext2 это на  J3?
5) Обязательно ли нужны диоды шоттки D1, D2, D3, D4?
6) Зачем для GSM модуля микрофон МК1, Он может передавать при звонке звуки с гаража?
7) У GSM модуля SIM800С где-то видел ставят делитель напряжения на RX или на TX, здесь видимо не требуется так как напряжения питания 4,5В? И еще для понижения этого напряжения диод D5 стоит.
8) есть ли разница если поставить вместо SIM800С, аналогичный но SIM800L он вроде как на пониженное энергопотребления расчитанный.

**Comment by AlexIII** [comment]
Посмотрите [схему](https://github.com/AlexIII/gsmGuard/blob/master/img/gg_sch_1.0.png)

Я уже не помню что-там за что отвечает. Все делалось для уменьшения энергопотребления и утечек тока.

**Comment by Metr-FM** [comment]
Хорошо понял Александр. 

А как запустить программу для настройки устройства?
В статье написано:
Настройка устройства, считывание логов событий и построение месячного графика температуры происходит с помощью утилиты (Python 2.7 + Tk + pyserial + matplotli).
То что в скобочках ничего не говорит для меня, Python 2.7 это видимо программа с версией, а остальное что такое?

Запуск любого файла в папке config-util не дает результата, что необходимо сделать чтобы запустить программу?

**Comment by AlexIII** [comment]
Используйте собранный exe, если не хотите разбираться как запускать из исходников 
https://github.com/AlexIII/gsmGuard/releases/tag/v1.3

**Comment by Metr-FM** [comment]
Запустил собранный exe.
Выдает что нет ответа от устройства.

**Comment by Metr-FM** [comment]
![Безымянный](https://user-images.githubusercontent.com/34219475/211010746-f7f9c35a-6820-44d6-b18d-7a133ac8d3c0.png)

**Comment by Metr-FM** [comment]
Залил прошивку hex файл gsmGuard-firmware-v1.3-RU-16MHz через XLoader, все прошло успешно.  Но связи с программой нет.

**Comment by AlexIII** [comment]
Много причин может быть. Отлаживать вам придется самостоятельно. Откройте терминал arduino 250000 bod, там должно появиться сообщение "USB connection detected. Awaiting config." Пока не появится, с программой связи не будет. На D12 должно быть +VCC чтобы войти в режим приема команд.

**Comment by Metr-FM** [comment]
Тогда понятно, я пока пытался только Ардуино с компьютером через программу состыковать без остальной схемотехники. В одном документе прочел что у вас еще есть изготовленная печатная плата, можно ли у Вас ее приобрести и как?

**Comment by AlexIII** [comment]
К сожалению, плат нет

**Comment by Metr-FM** [comment]
Понял, Александр. Буду собирать схему на макетной плате. Результаты после отпишусь.
